version: "3.7"
services:
  php:
    build:
      context: .
    volumes:
      - ..:/workspace
    command: apache2-foreground
    ports:
      - 8080:80
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=adminB4sh#77#
      - MYSQL_DATABASE=pw
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    
      # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '9090:80'
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=adminB4sh#77# 

volumes:
  mysql-data:
