version: "3.7"
services:
  web:
    image: nginx:1.17
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    user: vscode
    image: docker.pkg.github.com/krosf/dev-containers/php:7.4-fpm
    volumes:
      - ..:/workspace:cached
      - ../src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=adminB4sh#77#
      - MYSQL_DATABASE=pw
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    
      # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '9090:80'
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=adminB4sh#77# 

volumes:
  mysql-data:
